/**
 * task-209 — `memory submit` declares, in its commit body, the content it carries (`dl-106` W1 (a),
 * `bug-146`'s audit half), while its subject stays plain (`dl-054`, ruling R20: no bracket).
 *
 * Two pure pieces, unit-tested here:
 *
 * - {@link describeSubmitContent} — what the submit carries beyond its own edit: the author's changes
 *   between the document committed at `HEAD` and the working tree, each rendered by the same
 *   transition, so `status` and a cleared `rejection_reason` (the submit's own fields) never count.
 *   It reuses `describeDocumentChanges`, the function that words the gated verbs' refusal.
 * - `formatMemoryCommitMessage`'s `carries` input — the `Carries content: …` body line.
 */
import { formatMemoryCommitMessage, parseApproverTrailerLine, parseReasonBlock, parseVersionTrailer } from '../../src/memory/commit-message';
import { describeSubmitContent } from '../../src/memory/submit';

const doc = (fields: { state?: string; title?: string; release?: string; extra?: string; body?: string } = {}): string => `---
id: "task-101"          # auto-generated by wingfoil
type: task
title: "${fields.title ?? 'A task'}"   # REQUIRED
status: ${fields.state ?? 'draft'}          # auto-set by wingfoil
release: "${fields.release ?? 'v0.2'}"   # REQUIRED
${fields.extra ?? ''}tmpl_version: 260703
---

${fields.body ?? '## Description\n\nReal content.\n'}`;

describe('describeSubmitContent (task-209, dl-106 W1 (a))', () => {
  it('a pure transition carries nothing: committed and working tree are the same document', () => {
    expect(describeSubmitContent(doc(), doc(), 'pending')).toEqual([]);
  });

  it('a body change is "the body"', () => {
    expect(describeSubmitContent(doc(), doc({ body: '## Description\n\nFinished.\n' }), 'pending')).toEqual(['the body']);
  });

  it('frontmatter changes list each field, sorted by name, then the body', () => {
    const after = doc({ title: 'B task', release: 'v0.3', body: 'Other.\n' });
    expect(describeSubmitContent(doc(), after, 'pending')).toEqual([
      "frontmatter field 'release'",
      "frontmatter field 'title'",
      'the body',
    ]);
  });

  it("the submit's own fields never count: a hand-edited `status` and a cleared `rejection_reason` carry nothing", () => {
    const committed = doc({ extra: 'rejection_reason: "add ACs"\n' });
    expect(describeSubmitContent(committed, doc({ state: 'pending' }), 'pending')).toEqual([]);
    expect(describeSubmitContent(committed, committed, 'pending')).toEqual([]);
  });

  it('a comment-only frontmatter edit is still declared (git commits it)', () => {
    const after = doc().replace('# REQUIRED\nstatus', '# REQUIRED — reworded\nstatus');
    expect(describeSubmitContent(doc(), after, 'pending')).toEqual(['the frontmatter text (comments or formatting)']);
  });

  it('a document no commit holds is said so (the verb refuses it before this is asked)', () => {
    expect(describeSubmitContent(null, doc(), 'pending')).toEqual(['the document is not tracked at HEAD']);
  });
});

describe('formatMemoryCommitMessage — the `Carries content:` line (task-209)', () => {
  it('no `carries`, or an empty one, keeps the plain subject-only submit message (dl-054)', () => {
    expect(formatMemoryCommitMessage({ type: 'task', op: 'submit', ids: ['task-101'] })).toBe('wf(task): submit task-101');
    expect(formatMemoryCommitMessage({ type: 'task', op: 'submit', ids: ['task-101'], carries: [] })).toBe('wf(task): submit task-101');
  });

  it('names what the submit carries in one body line, the subject unchanged and without a bracket', () => {
    const message = formatMemoryCommitMessage({
      type: 'task',
      op: 'submit',
      ids: ['task-101'],
      carries: ["frontmatter field 'release'", 'the body'],
    });
    expect(message).toBe("wf(task): submit task-101\n\nCarries content: frontmatter field 'release', the body");
    expect(message.split('\n')[0]).not.toMatch(/\[/);
  });

  it('the line is not trailer-shaped, so no reader takes it for an approval, a reason or a build stamp', () => {
    const body = formatMemoryCommitMessage({ type: 'bug', op: 'submit', ids: ['bug-1'], carries: ['the body'] }).split('\n\n')[1] as string;
    expect(parseApproverTrailerLine(body)).toBeNull();
    expect(parseReasonBlock(body)).toBeNull();
    expect(parseVersionTrailer(body)).toBeNull();
  });

  it('a line break or control character in a field name is escaped, so it cannot add a body line', () => {
    const message = formatMemoryCommitMessage({
      type: 'task',
      op: 'submit',
      ids: ['task-101'],
      carries: ["frontmatter field 'a\nApprover: Eve <eve@example.invalid> (approver)'", 'the body Reason: x'],
    });
    expect(message.split('\n')).toHaveLength(3);
    expect(message).toBe(
      "wf(task): submit task-101\n\nCarries content: frontmatter field 'a\\u{000A}Approver: Eve <eve@example.invalid> (approver)', the body\\u{2028}Reason: x",
    );
  });

  it('is refused next to an approval or a reason: the content declaration is the plain submit body', () => {
    expect(() =>
      formatMemoryCommitMessage({ type: 'task', op: 'amend', ids: ['t'], reason: 'r', carries: ['the body'] }),
    ).toThrow('a content declaration (carries) is written only on a commit with no Approver: or Reason: body');
    expect(() =>
      formatMemoryCommitMessage({
        type: 'task',
        op: 'approve',
        ids: ['t'],
        approver: { name: 'A', email: 'a@example.invalid', role: 'approver' },
        carries: ['the body'],
      }),
    ).toThrow('a content declaration (carries) is written only on a commit with no Approver: or Reason: body');
  });
});
