/**
 * The allowlist of `name-resolvability.test.ts` (`task-151`, `dl-116` Q1 (B)): every backticked name
 * in a spec, ADR or requirement document that does not resolve in the repository, with the reason it
 * does not.
 *
 * An entry is keyed by document, class and name — never by line (`dl-075`) — and the list is sorted
 * by that key (the test enforces the order, the uniqueness and a non-empty reason). Reasons, by kind:
 *
 * - `retired on purpose`, `counterexample`, `example`, `example id`, `external`, `historical` — the
 *   name is quoted deliberately and should stay listed;
 * - `ADR_RECORD` — an ADR keeps the names of its time, because an ADR is not amended;
 * - `PLANNED` with `plannedBy` — the name occurs, literally, in the listed tasks, none of them `done`
 *   when the entry was written. Which of them implements it was not verified. Once every cited task is
 *   `done` and the name still does not resolve, the test reports the entry (warn) or fails (from v0.4);
 *   when the name ships, the entry goes stale and is reported;
 * - {@link scheduledIn} — the name is in the `features:` of a release that has no task for it yet
 *   (`release-planning` creates one when that release is planned); the entry is re-checked then;
 * - `UNTRIAGED` — a first-run finding nobody has looked at yet: stale, or not built, or quoted on
 *   purpose. The v0.3 warn release is when each one is fixed in its document (through `memory amend`
 *   for an approved spec) or given its real reason; from v0.4 an `UNTRIAGED` entry fails the gate.
 *
 * The first run's entries were generated from the findings at the task's base commit and classified
 * by the rule recorded in `task-151`'s Execution Notes. A new entry is written by hand, with its own
 * reason; `UNTRIAGED` is not a reason a new entry may use.
 */
import type { AllowlistEntry } from './support/name-resolvability';

/** An ADR is not amended (a change is a new ADR), so it keeps the names current or planned when it was accepted. */
export const ADR_RECORD =
  'ADR record: an ADR is not amended (a change is a new ADR), so it keeps the names current or planned when it was accepted';

/** Named in the entry's `plannedBy` tasks; spent once all of them are `done`. */
export const PLANNED =
  'planned: named in the non-done task(s) listed in plannedBy (literal match when the entry was written; the implementing task was not verified)';

/**
 * The reason of a name scheduled by a release's `features:` list with no task yet: `release` is the
 * release element id, `feature` the feature id that carries the name.
 */
export function scheduledIn(release: string, feature: string): string {
  return `scheduled: ${feature} is in ${release}'s features: list, which has no task for it yet; re-check when ${release} is planned`;
}

/** A first-run finding not yet fixed or justified; reported in warn mode, failing from v0.4. */
export const UNTRIAGED =
  'first run (task-151), untriaged: stale or not built yet; fix it by amending the document, or replace this reason with why the name is quoted on purpose';

/** Every allowed unresolved name, sorted by `document|class|name`. */
export const NAME_ALLOWLIST: readonly AllowlistEntry[] = [
  { document: 'docs/02_requirements/03_sard/01_architecture.md', nameClass: 'path', name: '.wingfoil/state/', reason: 'retired on purpose: REQ-SYS-03 forbids a state index, and the document names the path to say there is none' },
  { document: 'docs/02_requirements/03_sard/02_performance-nfr.md', nameClass: 'command', name: 'wingfoil agent execute', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/02_requirements/03_sard/02_performance-nfr.md', nameClass: 'command', name: 'wingfoil workflow next', reason: PLANNED, plannedBy: ['task-205', 'task-216', 'task-227', 'task-239', 'task-242'] },
  { document: 'docs/02_requirements/03_sard/03_state-context.md', nameClass: 'path', name: '.wingfoil/state/', reason: 'retired on purpose: REQ-SYS-03 forbids a state index, and the document names the path to say there is none' },
  { document: 'docs/02_requirements/03_sard/04_integrations.md', nameClass: 'command', name: 'wingfoil agent execute', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/02_requirements/03_sard/04_integrations.md', nameClass: 'command', name: 'wingfoil workflow status', reason: PLANNED, plannedBy: ['task-225', 'task-242'] },
  { document: 'docs/04_memory/design/adrs/adr-001-git-backed-storage.md', nameClass: 'config', name: 'tech_stack.storage', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/adrs/adr-001-git-backed-storage.md', nameClass: 'path', name: '.wingfoil/state/', reason: 'retired on purpose: REQ-SYS-03 forbids a state index, and the document names the path to say there is none' },
  { document: 'docs/04_memory/design/adrs/adr-003-declarative-workflow-engine.md', nameClass: 'command', name: 'wingfoil workflow start <name>', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/adrs/adr-004-mcp-over-stdio.md', nameClass: 'config', name: 'tech_stack.mcp', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/adrs/adr-007-stateless-state-derivation.md', nameClass: 'path', name: '.wingfoil/state/', reason: 'retired on purpose: REQ-SYS-03 forbids a state index, and the document names the path to say there is none' },
  { document: 'docs/04_memory/design/adrs/adr-008-per-type-state-machines.md', nameClass: 'path', name: '.wingfoil/state/', reason: 'retired on purpose: REQ-SYS-03 forbids a state index, and the document names the path to say there is none' },
  { document: 'docs/04_memory/design/adrs/adr-010-node-22-runtime-floor.md', nameClass: 'symbol', name: 'stripVTControlCharacters', reason: 'external: a Node.js `node:util` API, not a WingFoil symbol' },
  { document: 'docs/04_memory/design/adrs/adr-011-npm-staged-publishing-with-oidc.md', nameClass: 'symbol', name: 'NPM_TOKEN', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/adrs/adr-012-agent-execution-through-the-agent-cli.md', nameClass: 'command', name: 'wingfoil agent execute', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/adrs/adr-012-agent-execution-through-the-agent-cli.md', nameClass: 'config', name: 'gate.report', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/adrs/adr-012-agent-execution-through-the-agent-cli.md', nameClass: 'config', name: 'tests.unchanged', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/adrs/adr-012-agent-execution-through-the-agent-cli.md', nameClass: 'path', name: 'src/agent', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/adrs/adr-012-agent-execution-through-the-agent-cli.md', nameClass: 'symbol', name: 'agentExecute', reason: ADR_RECORD },
  { document: 'docs/04_memory/design/specs/spec-001-memory-yaml-schema.md', nameClass: 'config', name: 'defaults.amendable', reason: 'retired on purpose: the spec names the key to say it does not exist' },
  { document: 'docs/04_memory/design/specs/spec-001-memory-yaml-schema.md', nameClass: 'symbol', name: 'E_INVALID_MEMORY_SCHEMA', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-001-memory-yaml-schema.md', nameClass: 'symbol', name: 'E_INVALID_STATE_GRAPH', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-002-dna-yaml-schema.md', nameClass: 'path', name: 'docs/self/.wingfoil/dna.yaml', reason: 'historical: the pre-task-111 location, named where the document records that task-111 moved it (a dated Revision or Process note, or a "moved from" clause)' },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'command', name: 'wingfoil agent execute', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'command', name: 'wingfoil workflow finalize', reason: PLANNED, plannedBy: ['task-226'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'command', name: 'wingfoil workflow start', reason: PLANNED, plannedBy: ['task-217', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'config', name: 'approval.by_person', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'config', name: 'tests.unchanged', reason: PLANNED, plannedBy: ['task-185', 'task-205'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'path', name: '.wingfoil/workflows/bindings.yaml', reason: PLANNED, plannedBy: ['task-175', 'task-199'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'path', name: 'bindings.yaml', reason: PLANNED, plannedBy: ['task-175', 'task-199', 'task-221', 'task-222'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'path', name: 'docs/self/', reason: 'historical: the pre-task-111 location, named where the document records that task-111 moved it (a dated Revision or Process note, or a "moved from" clause)' },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'ActionBinding.manual', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'ActionBinding.run', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'CheckBinding.run', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'CheckBinding.severity', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'E_PHASE_APPROVER_UNKNOWN', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'E_PHASE_DISTINCT_FROM_SELF', reason: PLANNED, plannedBy: ['task-185'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'E_PHASE_DISTINCT_FROM_UNKNOWN', reason: PLANNED, plannedBy: ['task-185'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'E_PHASE_EXECUTOR_WITHOUT_ROLE', reason: PLANNED, plannedBy: ['task-185'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'E_PHASE_MODE_NOT_INDEPENDENT', reason: PLANNED, plannedBy: ['task-185'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'E_PHASE_ROLE_UNKNOWN', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'E_WORKFLOW_COLLECTION_UNRESOLVED', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'E_WORKFLOW_ELEMENT_TYPE_UNKNOWN', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'W_PHASE_EXIT_STATE_UNDETERMINED', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'W_PHASE_FALLBACK_NOT_REENTRANT', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'W_PHASE_FALLBACK_STATE_MISMATCH', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-003-workflows-yaml-schema.md', nameClass: 'symbol', name: 'W_PHASE_TOKEN_OUT_OF_SCOPE', reason: PLANNED, plannedBy: ['task-194', 'task-199'] },
  { document: 'docs/04_memory/design/specs/spec-004-mcp-surface-contract.md', nameClass: 'element', name: 'task-042-foo', reason: 'example id: an illustrative element id, not a real element' },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil agent execute', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil agent list', reason: PLANNED, plannedBy: ['task-206', 'task-216', 'task-228', 'task-240', 'task-243'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil agent show', reason: PLANNED, plannedBy: ['task-206', 'task-220', 'task-228', 'task-243'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil audit', reason: scheduledIn('minor-v0.4', 'P5.1.3') },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil dna infer', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil memory import', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil workflow create', reason: PLANNED, plannedBy: ['task-211'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil workflow end', reason: PLANNED, plannedBy: ['task-217'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil workflow finalize', reason: PLANNED, plannedBy: ['task-226'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil workflow next', reason: PLANNED, plannedBy: ['task-205', 'task-216', 'task-227', 'task-239', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil workflow remove', reason: PLANNED, plannedBy: ['task-211'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil workflow show', reason: PLANNED, plannedBy: ['task-199', 'task-204', 'task-212', 'task-221', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil workflow start', reason: PLANNED, plannedBy: ['task-217', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'command', name: 'wingfoil workflow status', reason: PLANNED, plannedBy: ['task-225', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'config', name: 'dna.infer', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'config', name: 'memory.import', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'config', name: 'workflow.create', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'config', name: 'workflow.end', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'config', name: 'workflow.finalize', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'config', name: 'workflow.start', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'path', name: '.wingfoil/run/', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'path', name: 'src/agent', reason: PLANNED, plannedBy: ['task-177', 'task-206', 'task-218'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'NextResult', reason: PLANNED, plannedBy: ['task-216', 'task-235', 'task-239'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'StatusResult', reason: PLANNED, plannedBy: ['task-216', 'task-225', 'task-239'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'W_UNCOMMITTED_INPUTS', reason: PLANNED, plannedBy: ['task-198', 'task-240'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'agentAdvanceStep', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'agentExecute', reason: PLANNED, plannedBy: ['task-218'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'agentList', reason: PLANNED, plannedBy: ['task-240'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'agentResolveNext', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'agentShow', reason: PLANNED, plannedBy: ['task-220'] },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'dnaInfer', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'memoryImport', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'pathsQuery', reason: 'historical: the 2026-09-17 Revision note quotes the function name §3 carried before task-165 renamed the row to the registered op `paths` (dl-046 C)' },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'workflowCreate', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'workflowEnd', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'workflowFinalize', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'workflowNext', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-006-core-domain-api.md', nameClass: 'symbol', name: 'workflowStatus', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-007-secret-hygiene-patterns.md', nameClass: 'command', name: 'wingfoil audit', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-007-secret-hygiene-patterns.md', nameClass: 'path', name: '.wingfoil/security-ignore', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-007-secret-hygiene-patterns.md', nameClass: 'path', name: 'docs/self/.wingfoil/', reason: 'historical: the pre-task-111 location, named where the document records that task-111 moved it (a dated Revision or Process note, or a "moved from" clause)' },
  { document: 'docs/04_memory/design/specs/spec-007-secret-hygiene-patterns.md', nameClass: 'path', name: 'docs/self/docs/04_memory/', reason: 'historical: the pre-task-111 location, named where the document records that task-111 moved it (a dated Revision or Process note, or a "moved from" clause)' },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'command', name: 'wingfoil dna add --field stacks.technologies --value Go --version 1.22', reason: 'historical: a dated Revision note quoting a pre-dl-082 invocation and what it printed' },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'command', name: 'wingfoil memroy add', reason: 'counterexample: a deliberately misspelt noun, quoted to show the unknown-command error' },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'command', name: 'wingfoil nosuchnoun', reason: 'counterexample: an unknown noun, quoted to show the unknown-command error' },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'command', name: 'wingfoil workflow status', reason: PLANNED, plannedBy: ['task-225', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'config', name: 'tech_stack.cli', reason: 'historical: the Process Notes record the dna.yaml key the spec was cross-checked against, before spec-002 replaced `tech_stack` with `stacks`' },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'symbol', name: 'E_UNKNOWN_COMMAND', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'symbol', name: 'NO_COLOR', reason: 'external: the no-color.org environment variable; no WingFoil code reads it yet (commander uses it only to strip help colour, and the help has none); spec-008 §2 declares the rule the colour P5.1.4 adds must honour (task-156, bug-203)' },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'symbol', name: 'W_UNCOMMITTED_INPUTS', reason: PLANNED, plannedBy: ['task-198', 'task-240'] },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'symbol', name: 'flags.noColor', reason: 'counterexample: spec-008 names the property to forbid inventing it (Commander derives `color`/`interactive` from the `--no-*` flags)' },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'symbol', name: 'noColor', reason: 'counterexample: spec-008 names the property to forbid inventing it (Commander derives `color`/`interactive` from the `--no-*` flags)' },
  { document: 'docs/04_memory/design/specs/spec-008-cli-grammar.md', nameClass: 'symbol', name: 'noInteractive', reason: 'counterexample: spec-008 names the property to forbid inventing it (Commander derives `color`/`interactive` from the `--no-*` flags)' },
  { document: 'docs/04_memory/design/specs/spec-009-validation-strategy.md', nameClass: 'config', name: 'wingfoil.type', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-009-validation-strategy.md', nameClass: 'symbol', name: 'E_INVALID_DNA_YAML_SCHEMA', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-009-validation-strategy.md', nameClass: 'symbol', name: 'E_INVALID_GATES_REF', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-009-validation-strategy.md', nameClass: 'symbol', name: 'E_INVALID_MEMORY_YAML_SCHEMA', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-009-validation-strategy.md', nameClass: 'symbol', name: 'E_INVALID_WORKFLOWS_YAML_SCHEMA', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-010-memory-frontmatter-schema.md', nameClass: 'command', name: 'wingfoil memory show', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-010-memory-frontmatter-schema.md', nameClass: 'config', name: 'states.initial', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-010-memory-frontmatter-schema.md', nameClass: 'element', name: 'task-042-implement-cli-grammar', reason: 'example id: an illustrative element id, not a real element' },
  { document: 'docs/04_memory/design/specs/spec-010-memory-frontmatter-schema.md', nameClass: 'path', name: '.wingfoil/state/', reason: 'retired on purpose: REQ-SYS-03 forbids a state index, and the document names the path to say there is none' },
  { document: 'docs/04_memory/design/specs/spec-010-memory-frontmatter-schema.md', nameClass: 'path', name: 'F-04-frontmatter-schema.md', reason: 'retired on purpose: the prior-art draft the spec says it departs from' },
  { document: 'docs/04_memory/design/specs/spec-011-storage-layout.md', nameClass: 'path', name: '.assignments.yaml', reason: 'retired on purpose: the spec names the file to say `.wingfoil/` does not contain it' },
  { document: 'docs/04_memory/design/specs/spec-011-storage-layout.md', nameClass: 'path', name: 'agents.yaml', reason: 'retired on purpose: the spec names the file to say `.wingfoil/` does not contain it' },
  { document: 'docs/04_memory/design/specs/spec-011-storage-layout.md', nameClass: 'path', name: 'docs/self/', reason: 'historical: the pre-task-111 location, named where the document records that task-111 moved it (a dated Revision or Process note, or a "moved from" clause)' },
  { document: 'docs/04_memory/design/specs/spec-011-storage-layout.md', nameClass: 'path', name: 'docs/self/.wingfoil/', reason: 'historical: the pre-task-111 location, named where the document records that task-111 moved it (a dated Revision or Process note, or a "moved from" clause)' },
  { document: 'docs/04_memory/design/specs/spec-011-storage-layout.md', nameClass: 'path', name: 'docs/self/.wingfoil/directives/custom/', reason: 'historical: the pre-task-111 location, named where the document records that task-111 moved it (a dated Revision or Process note, or a "moved from" clause)' },
  { document: 'docs/04_memory/design/specs/spec-011-storage-layout.md', nameClass: 'path', name: 'docs/self/docs/04_memory/', reason: 'historical: the pre-task-111 location, named where the document records that task-111 moved it (a dated Revision or Process note, or a "moved from" clause)' },
  { document: 'docs/04_memory/design/specs/spec-012-context-loader-relevance-filtering.md', nameClass: 'command', name: 'wingfoil agent execute [--next]', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/04_memory/design/specs/spec-012-context-loader-relevance-filtering.md', nameClass: 'symbol', name: 'assertEqual', reason: 'example: generic test pseudo-code, not a WingFoil symbol' },
  { document: 'docs/04_memory/design/specs/spec-015-packaging-publishing.md', nameClass: 'path', name: 'docs/user-docs-v0.2', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-015-packaging-publishing.md', nameClass: 'symbol', name: 'NPM_TOKEN', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'command', name: 'wingfoil agent execute', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'command', name: 'wingfoil agent execute --workflow <instance-id> --step <key>', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'command', name: 'wingfoil agent execute [--next] [--role ROLE] [--element TYPE:ID]', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'command', name: 'wingfoil agent execute|list|show', reason: PLANNED, plannedBy: ['task-199', 'task-216', 'task-220', 'task-240'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'command', name: 'wingfoil agent list', reason: PLANNED, plannedBy: ['task-206', 'task-216', 'task-228', 'task-240', 'task-243'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'command', name: 'wingfoil agent show', reason: PLANNED, plannedBy: ['task-206', 'task-220', 'task-228', 'task-243'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'command', name: 'wingfoil agent show <run-id>', reason: PLANNED, plannedBy: ['task-206', 'task-220', 'task-228', 'task-243'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'gate.report', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'launch.headless.args', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'launch.headless.output', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'launch.interactive.args', reason: PLANNED, plannedBy: ['task-228', 'task-236'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'launch.interactive.terminal', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'mcp.template', reason: PLANNED, plannedBy: ['task-177'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'mcp.via', reason: PLANNED, plannedBy: ['task-177'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'prompt.via', reason: PLANNED, plannedBy: ['task-177', 'task-236'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'session.assign_args', reason: PLANNED, plannedBy: ['task-177', 'task-228'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'session.field', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'session.id', reason: PLANNED, plannedBy: ['task-177', 'task-228'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'session.lookup_args', reason: PLANNED, plannedBy: ['task-177'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'session.resume', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'session.resume.args', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'session.resume.supported', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'summary.export_args', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'tokens.input', reason: PLANNED, plannedBy: ['task-220'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'usage.fields', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'usage.from', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'config', name: 'usage.lookup_args', reason: PLANNED, plannedBy: ['task-177'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'path', name: '.wingfoil/agents.yaml', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'path', name: '.wingfoil/agents/', reason: PLANNED, plannedBy: ['task-177', 'task-196'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'path', name: '.wingfoil/run/', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'path', name: '.wingfoil/state/', reason: 'retired on purpose: REQ-SYS-03 forbids a state index, and the document names the path to say there is none' },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'path', name: 'src/agent', reason: PLANNED, plannedBy: ['task-177', 'task-206', 'task-218'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'path', name: 'test/fixtures/agents/custom/fake.yaml', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'path', name: 'test/fixtures/agents/fake-agent.cjs', reason: PLANNED, plannedBy: ['task-200'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'AGENT_NOT_FOUND', reason: PLANNED, plannedBy: ['task-218'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'INVALID_CONTEXT', reason: PLANNED, plannedBy: ['task-218'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'MCP_UNREACHABLE', reason: PLANNED, plannedBy: ['task-218'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'NO_AGENT', reason: PLANNED, plannedBy: ['task-218'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'NO_NEXT_STEP', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'NO_RUN_LOG', reason: PLANNED, plannedBy: ['task-218'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'NO_STEP_ELEMENT', reason: PLANNED, plannedBy: ['task-235'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'NO_STEP_ROLE', reason: PLANNED, plannedBy: ['task-235'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'NO_TERMINAL', reason: PLANNED, plannedBy: ['task-200', 'task-218'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'NextResult.next', reason: PLANNED, plannedBy: ['task-235'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'W_UNCOMMITTED_INPUTS', reason: PLANNED, plannedBy: ['task-198', 'task-240'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'agentAdvanceStep', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'agentExecute', reason: PLANNED, plannedBy: ['task-218'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'agentList', reason: PLANNED, plannedBy: ['task-240'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'agentResolveNext', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'agentRole', reason: PLANNED, plannedBy: ['task-216', 'task-240'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'agentShow', reason: PLANNED, plannedBy: ['task-220'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'allowedModes', reason: PLANNED, plannedBy: ['task-216'] },
  { document: 'docs/04_memory/design/specs/spec-016-agent-execution.md', nameClass: 'symbol', name: 'distinctFrom', reason: PLANNED, plannedBy: ['task-216'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil agent execute --next', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil agent execute --workflow <instance-id> --step <key>', reason: PLANNED, plannedBy: ['task-149', 'task-176', 'task-178', 'task-195', 'task-198', 'task-199', 'task-200', 'task-206', 'task-216', 'task-217', 'task-218', 'task-228', 'task-235', 'task-236', 'task-237', 'task-242', 'task-243', 'task-245'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil memory add … --workflow <ref> [--step <key>]', reason: PLANNED, plannedBy: ['task-217', 'task-227'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil workflow create', reason: PLANNED, plannedBy: ['task-211'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil workflow end', reason: PLANNED, plannedBy: ['task-217'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil workflow finalize', reason: PLANNED, plannedBy: ['task-226'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil workflow next', reason: PLANNED, plannedBy: ['task-205', 'task-216', 'task-227', 'task-239', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil workflow remove', reason: PLANNED, plannedBy: ['task-211'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil workflow show', reason: PLANNED, plannedBy: ['task-199', 'task-204', 'task-212', 'task-221', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil workflow start', reason: PLANNED, plannedBy: ['task-217', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'command', name: 'wingfoil workflow status', reason: PLANNED, plannedBy: ['task-225', 'task-242'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'config', name: 'workflow.create', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'config', name: 'workflow.end', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'config', name: 'workflow.finalize', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'config', name: 'workflow.next', reason: PLANNED, plannedBy: ['task-239'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'config', name: 'workflow.start', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'path', name: '.wingfoil/state/', reason: 'retired on purpose: REQ-SYS-03 forbids a state index, and the document names the path to say there is none' },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'path', name: 'bindings.yaml', reason: PLANNED, plannedBy: ['task-175', 'task-199', 'task-221', 'task-222'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'ListResult', reason: PLANNED, plannedBy: ['task-204'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'NextResult', reason: PLANNED, plannedBy: ['task-216', 'task-235', 'task-239'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'NextResult.next', reason: PLANNED, plannedBy: ['task-235'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'StatusResult', reason: PLANNED, plannedBy: ['task-216', 'task-225', 'task-239'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_APPROVAL_ROLE_WITHOUT_AUTHORITY', reason: PLANNED, plannedBy: ['task-225'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_INSTANCE_WORKFLOW_UNKNOWN', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_MEMORY_INVALID_STATE', reason: PLANNED, plannedBy: ['task-198'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_MEMORY_UNREADABLE', reason: PLANNED, plannedBy: ['task-171', 'task-198'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_PHASE_EXIT_STATE_UNDETERMINED', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_PHASE_FALLBACK_NOT_REENTRANT', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_PHASE_FALLBACK_STATE_MISMATCH', reason: PLANNED, plannedBy: ['task-194'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_PHASE_TOKEN_OUT_OF_SCOPE', reason: PLANNED, plannedBy: ['task-194', 'task-199'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_UNCOMMITTED_INPUTS', reason: PLANNED, plannedBy: ['task-198', 'task-240'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'W_UNRESOLVED_TOKEN', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'agentRole', reason: PLANNED, plannedBy: ['task-216', 'task-240'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'allowedModes', reason: PLANNED, plannedBy: ['task-216'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'executableNow', reason: PLANNED, plannedBy: ['task-204'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'routedTo', reason: PLANNED, plannedBy: ['task-225'] },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'workflowCreate', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'workflowEnd', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'workflowFinalize', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'workflowNext', reason: UNTRIAGED },
  { document: 'docs/04_memory/design/specs/spec-017-workflow-commands-and-state-deduction.md', nameClass: 'symbol', name: 'workflowStatus', reason: UNTRIAGED },
];
