/**
 * P1.6 (US-3-09) — `wingfoil memory submit` core-op fit criteria, per
 * `docs/02_requirements/02_bdd/features/p1-memory/P1.6-memory-submit.feature` (all three scenarios),
 * `dl-032-illegal-transition-message-contract` (the pinned illegal-transition message, exit `1`),
 * `spec-010-memory-frontmatter-schema` (submit sets `status`, removes `rejection_reason`; title and
 * every `template.frontmatter.required` field must be non-empty once `status` leaves `draft`),
 * `spec-004-mcp-surface-contract` §4.3 (one commit, subject `wf({type}): {verb} {id}`),
 * `spec-008-cli-grammar` §5/§7 (bare `<id>`; not found → `1`; missing argument → `2`) and
 * REQ-SEC-01 (git-identity pre-flight).
 *
 * Exercises the REAL, registered `CORE_MODULES` `memory.memorySubmit` operation — the exact `CoreFn`
 * the CLI command and the MCP Tool dispatch to. Every write lands in a THROWAWAY temp git repo.
 *
 * The `task` fixture type carries the REAL `task` state machine from `.wingfoil/memory.yaml`
 * (not the default machine), because P1.6's pinned message must hold against the machine this project
 * actually runs — there `approved` is a `waiting` state whose forward edge is `done`, not `pending`.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { beginMemoryTransition, commitMemoryTransition, CORE_MODULES } from '../../src/core';
import type { CoreFn } from '../../src/core/registry';
import { exitCodeForResult, exitCodeForThrow } from '../../src/core/exit-code';
import { UsageError } from '../../src/core/usage-error';
import { commitAll, makeTempGitRepo, removeTempDir, writeFixtureFile } from '../storage/helpers/git-fixture';
import { STAMP_TRAILER } from '../storage/helpers/stamp-trailer';

const MEMORY_YAML = `version: 1
defaults:
  states:
    sequence: [draft, pending, approved]
    gates:
      pending: { reject: draft }
types:
  task:
    path: "docs/memory/{release}/{id}.md"
    template:
      file: "memory/templates/task.md"
      frontmatter:
        required: [title, release]
    states:
      sequence: [draft, pending, backlog, in-progress, in-review, approved, done]
      gates:
        pending: { reject: draft }
        in-review: { reject: in-progress }
      waiting: [backlog, approved]
  note:
    path: "docs/memory/note/{id}.md"
`;

interface SubmitValue {
  readonly id: string;
  readonly path: string;
  readonly from: string;
  readonly to: string;
}

/** The real, registered `memory.memorySubmit` `CoreFn` — fails loudly if a future change un-registers it. */
function memorySubmitFn(): CoreFn<unknown, SubmitValue> {
  const operation = CORE_MODULES.find((module) => module.name === 'memory')?.operations.memorySubmit;
  if (!operation) throw new Error('fixture bug: "memorySubmit" operation not registered on the memory module');
  return operation.fn as CoreFn<unknown, SubmitValue>;
}

function memoryHistoryFn(): CoreFn<unknown, { entries: { operation: string | null; from: string | null; to: string | null }[] }> {
  const operation = CORE_MODULES.find((module) => module.name === 'memory')?.operations.memoryHistory;
  if (!operation) throw new Error('fixture bug: "memoryHistory" operation not registered');
  return operation.fn as CoreFn<unknown, { entries: { operation: string | null; from: string | null; to: string | null }[] }>;
}

function gitOut(repo: string, args: string[]): string {
  return execFileSync('git', ['-C', repo, ...args], { encoding: 'utf-8' }).trim();
}
const head = (repo: string): string => gitOut(repo, ['rev-parse', 'HEAD']);

function taskDoc(fields: { id: string; status: string; title?: string; release?: string; extra?: string }): string {
  return `---
id: "${fields.id}"          # auto-generated by wingfoil
type: task
title: "${fields.title ?? 'A task'}"   # REQUIRED
status: ${fields.status}          # auto-set by wingfoil
release: "${fields.release ?? 'v0.2'}"   # REQUIRED
${fields.extra ?? ''}tmpl_version: 260703
---

## Description

Real content.
`;
}

describe('CORE_MODULES memory.memorySubmit — P1.6 fit criteria', () => {
  let repo: string;

  beforeEach(() => {
    repo = makeTempGitRepo();
    writeFixtureFile(repo, '.wingfoil/memory.yaml', MEMORY_YAML);
    writeFixtureFile(repo, 'docs/memory/v0.2/task-101.md', taskDoc({ id: 'task-101', status: 'draft' }));
    writeFixtureFile(repo, 'docs/memory/v0.2/task-200.md', taskDoc({ id: 'task-200', status: 'approved' }));
    commitAll(repo, 'seed');
  });

  afterEach(() => removeTempDir(repo));

  it('P1.6 sc.1: moves a draft to `status: pending`, in exactly one scoped `wf(task): submit task-101` commit, exit 0', async () => {
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-101', positionals: ['task-101'] });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(exitCodeForResult(result)).toBe(0);
    expect(result.value).toEqual({ id: 'task-101', path: 'docs/memory/v0.2/task-101.md', from: 'draft', to: 'pending' });

    const content = readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8');
    // Only the status value changed; its inline comment and every other byte survive.
    expect(content).toBe(taskDoc({ id: 'task-101', status: 'draft' }).replace('status: draft', 'status: pending'));

    // The transition is recorded in git: one new commit, subject only, scoped to the one file.
    expect(gitOut(repo, ['rev-list', '--count', `${before}..HEAD`])).toBe('1');
    expect(result.commit).toEqual({ sha: head(repo), message: 'wf(task): submit task-101' });
    expect(gitOut(repo, ['log', '-1', '--format=%B'])).toBe(`wf(task): submit task-101${STAMP_TRAILER}`);
    expect(gitOut(repo, ['show', '--name-only', '--format=', 'HEAD'])).toBe('docs/memory/v0.2/task-101.md');
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');
  });

  it('commits the content the author wrote before submitting (submit = fill content + move state, one commit)', async () => {
    const path = join(repo, 'docs/memory/v0.2/task-101.md');
    writeFileSync(path, readFileSync(path, 'utf-8').replace('Real content.', 'Real content, now finished.'));
    const result = await memorySubmitFn()({ root: repo, positional: 'task-101' });
    expect(result.ok).toBe(true);
    expect(gitOut(repo, ['show', 'HEAD:docs/memory/v0.2/task-101.md'])).toContain('Real content, now finished.');
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');
  });

  it('bug-027: a change someone else staged is NOT swept into the `wf(task): submit` commit, and stays staged', async () => {
    writeFixtureFile(repo, 'other.txt', 'unrelated work');
    gitOut(repo, ['add', 'other.txt']);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-101' });
    expect(result.ok).toBe(true);
    expect(gitOut(repo, ['show', '--name-only', '--format=', 'HEAD'])).toBe('docs/memory/v0.2/task-101.md');
    expect(gitOut(repo, ['diff', '--cached', '--name-only'])).toBe('other.txt');
  });

  it('removes a multi-paragraph block-scalar `rejection_reason` without corrupting `status` (second-pass rejection repro)', async () => {
    const doc = taskDoc({ id: 'task-107', status: 'draft' }).replace(
      'status: draft          # auto-set by wingfoil\n',
      'status: draft          # auto-set by wingfoil\nrejection_reason: |\n  First paragraph.\n\n  Second paragraph.\n',
    );
    writeFixtureFile(repo, 'docs/memory/v0.2/task-107.md', doc);
    commitAll(repo, 'seed 107');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-107' });
    expect(result.ok).toBe(true);
    const written = readFileSync(join(repo, 'docs/memory/v0.2/task-107.md'), 'utf-8');
    expect(written).toBe(taskDoc({ id: 'task-107', status: 'pending' }));
  });

  it('post-condition: a rendered document whose re-parsed frontmatter is not the target is refused — nothing written, no commit', () => {
    const before = head(repo);
    const path = join(repo, 'docs/memory/v0.2/task-101.md');
    const original = readFileSync(path, 'utf-8');
    const prepared = beginMemoryTransition(repo, 'task-101', 'submit');
    expect(prepared.ok).toBe(true);
    if (!prepared.ok) return;
    // A corrupted render of the kind the first pass produced: a stray continuation line folded into `status`.
    const corrupted = prepared.value.content.replace('status: draft', 'status: pending\n  Second paragraph.');
    const result = commitMemoryTransition(repo, prepared.value, corrupted, 'wf(task): submit task-101', { status: 'pending' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('VALIDATION');
    // "the rendered DOCUMENT", not "the rendered frontmatter", since task-088: the pre-write
    // post-condition covers the body as well as the frontmatter fields, so naming only the
    // frontmatter would mislabel a body problem (`verifyDocumentEdit`, `bug-076`).
    expect(result.error.message).toBe(
      'refusing to write docs/memory/v0.2/task-101.md: the rendered document failed its post-condition: field \'status\' is "pending Second paragraph.", expected "pending"',
    );
    expect(exitCodeForResult(result)).toBe(1);
    expect(readFileSync(path, 'utf-8')).toBe(original);
    expect(head(repo)).toBe(before);
  });

  it('P1.6 sc.2: an illegal transition (approved -> pending) leaves the state unchanged and exits 1 with the pinned message', async () => {
    const before = head(repo);
    const original = readFileSync(join(repo, 'docs/memory/v0.2/task-200.md'), 'utf-8');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-200' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('INVALID_TRANSITION');
    expect(result.error.message).toBe("illegal transition approved -> pending for type 'task'");
    expect(exitCodeForResult(result)).toBe(1);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-200.md'), 'utf-8')).toBe(original);
    expect(head(repo)).toBe(before);
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');
  });

  it('P1.6 sc.3: a non-existent document exits 1 with `document not found: task-999`', async () => {
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-999' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('NOT_FOUND');
    expect(result.error.message).toBe('document not found: task-999');
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
  });

  it('a missing or blank `<id>` is a usage error (exit 2) — spec-008 §5/§7', async () => {
    for (const positional of [undefined, '  ']) {
      await expect(memorySubmitFn()({ root: repo, positional })).rejects.toBeInstanceOf(UsageError);
      try {
        await memorySubmitFn()({ root: repo, positional });
      } catch (error) {
        expect(exitCodeForThrow(error)).toEqual({ reason: 'missing required argument: <id>', exitCode: 2 });
      }
    }
  });

  it('spec-010: an empty required field refuses the submit (exit 1), naming every missing field in declared order, writing nothing', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/task-102.md', taskDoc({ id: 'task-102', status: 'draft', title: '', release: '' }));
    commitAll(repo, 'seed 102');
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-102' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('VALIDATION');
    expect(result.error.message).toBe('missing required field on submit: title, release');
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-102.md'), 'utf-8')).toContain('status: draft');
  });

  it('spec-010: a resubmit after a reject removes `rejection_reason` from the frontmatter', async () => {
    writeFixtureFile(
      repo,
      'docs/memory/v0.2/task-103.md',
      taskDoc({ id: 'task-103', status: 'draft', extra: 'rejection_reason: "add the missing tests"\n' }),
    );
    commitAll(repo, 'seed 103');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-103' });
    expect(result.ok).toBe(true);
    const content = readFileSync(join(repo, 'docs/memory/v0.2/task-103.md'), 'utf-8');
    expect(content).not.toContain('rejection_reason');
    expect(content).toBe(taskDoc({ id: 'task-103', status: 'pending' }));
  });

  it('drives every plain forward edge, not only draft: in-progress -> in-review (spec-001)', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/task-104.md', taskDoc({ id: 'task-104', status: 'in-progress' }));
    commitAll(repo, 'seed 104');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-104' });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.to).toBe('in-review');
    expect(result.commit?.message).toBe('wf(task): submit task-104');
  });

  it('a type without its own machine falls back to `defaults.states` (REQ-STATE-08)', async () => {
    writeFixtureFile(repo, 'docs/memory/note/note-1.md', '---\nid: note-1\ntype: note\ntitle: "N"\nstatus: draft\n---\nbody\n');
    commitAll(repo, 'seed note');
    const result = await memorySubmitFn()({ root: repo, positional: 'note-1' });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.to).toBe('pending');
    expect(result.commit?.message).toBe('wf(note): submit note-1');
  });

  it('a `status` that is not a state of the type exits 1 with the task-036 message, writing nothing', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/task-105.md', taskDoc({ id: 'task-105', status: 'shipped' }));
    commitAll(repo, 'seed 105');
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-105' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('VALIDATION');
    expect(result.error.message).toBe("invalid state 'shipped' for type 'task'");
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
  });

  it('a document with no `status` at all is an invalid state (exit 1), reported without the text `undefined`', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/task-106.md', '---\nid: task-106\ntype: task\ntitle: "T"\nrelease: "v0.2"\n---\n');
    commitAll(repo, 'seed 106');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-106' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe("invalid state '' for type 'task'");
    expect(exitCodeForResult(result)).toBe(1);
  });

  it('a document whose `type` is not registered exits 1 with the `memory add` unknown-type message', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/odd.md', '---\nid: odd-1\ntype: unicorn\ntitle: "U"\nstatus: draft\n---\n');
    commitAll(repo, 'seed odd');
    const result = await memorySubmitFn()({ root: repo, positional: 'odd-1' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('NOT_FOUND');
    expect(result.error.message).toBe("unknown memory type 'unicorn' (not defined in memory.yaml)");
  });

  it('`memory history` reads the submit back as operation `submit`, draft -> pending (P1.10 round-trip)', async () => {
    await memorySubmitFn()({ root: repo, positional: 'task-101' });
    const history = await memoryHistoryFn()({ root: repo, positional: 'task-101' });
    expect(history.ok).toBe(true);
    if (!history.ok) return;
    const last = history.value.entries[history.value.entries.length - 1];
    expect(last).toMatchObject({ operation: 'submit', from: 'draft', to: 'pending' });
  });
});

/**
 * task-168 — `dl-124` (Q1 (A), Q2 (a), Q3 (ii)): a required field the type declares in
 * `template.frontmatter.not_applicable_allowed` may hold `"n/a — <reason>"`; bare `n/a`, or the value
 * on an undeclared field, is refused naming the field. `kind` is required and NOT declared, the shape
 * task-150 gave this repository's `task.kind`: a not-applicable value must not let it be skipped.
 */
describe('CORE_MODULES memory.memorySubmit — declared not-applicable values (task-168, dl-124)', () => {
  const RELEASE_YAML = `version: 1
types:
  release:
    path: "docs/memory/planning/{id}.md"
    template:
      file: "memory/templates/release.md"
      frontmatter:
        required: [title, kind, pillar, requirements]
        not_applicable_allowed: [pillar, requirements]
    states:
      sequence: [draft, planning, in-development]
      waiting: [planning]
`;
  const PATH = 'docs/memory/planning/patch-v0.9.1.md';
  const release = (fields: { kind?: string; pillar?: string; requirements?: string }): string => `---
id: "patch-v0.9.1"
type: release
title: "A patch"
status: draft
kind: "${fields.kind ?? 'patch'}"
pillar: "${fields.pillar ?? 'n/a — patch release'}"
requirements: "${fields.requirements ?? 'n/a — no per-release backlog for a patch'}"
tmpl_version: 260703
---

Body.
`;
  let repo: string;

  beforeEach(() => {
    repo = makeTempGitRepo();
    writeFixtureFile(repo, '.wingfoil/memory.yaml', RELEASE_YAML);
  });

  afterEach(() => removeTempDir(repo));

  async function submitWith(fields: Parameters<typeof release>[0]): ReturnType<ReturnType<typeof memorySubmitFn>> {
    writeFixtureFile(repo, PATH, release(fields));
    commitAll(repo, 'seed');
    return memorySubmitFn()({ root: repo, positional: 'patch-v0.9.1' });
  }

  it('AC1: declared fields holding "n/a — <reason>" pass the submit (exit 0, draft -> planning)', async () => {
    const result = await submitWith({});
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.to).toBe('planning');
    expect(gitOut(repo, ['log', '-1', '--format=%s'])).toBe('wf(release): submit patch-v0.9.1');
  });

  it('AC1: bare `n/a` in a declared field is refused (exit 1) naming the field, nothing written', async () => {
    const result = await submitWith({ pillar: 'n/a' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(exitCodeForResult(result)).toBe(1);
    expect(result.error.code).toBe('VALIDATION');
    expect(result.error.message).toBe(
      'not-applicable value on submit: pillar needs a reason, written "n/a — <reason>"',
    );
    expect(gitOut(repo, ['log', '-1', '--format=%s'])).toBe('seed');
    expect(readFileSync(join(repo, PATH), 'utf-8')).toContain('status: draft');
  });

  it('AC1: an undeclared required field (`kind`) holding a not-applicable value is refused (exit 1) naming the field', async () => {
    const result = await submitWith({ kind: 'n/a — patch release' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(exitCodeForResult(result)).toBe(1);
    expect(result.error.message).toBe(
      "not-applicable value on submit: kind does not accept one (type 'release' does not list it in template.frontmatter.not_applicable_allowed)",
    );
  });

  it('a missing field and a refused not-applicable value are both reported, missing first', async () => {
    const result = await submitWith({ kind: '', pillar: 'n/a' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe(
      'missing required field on submit: kind; not-applicable value on submit: pillar needs a reason, written "n/a — <reason>"',
    );
  });
});

/**
 * bug-147 (task-168, approver ruling Q-A (1), 2026-10-02): an author's explicit `features: []` is
 * filled, and this repository's own `release` scaffold leaves `features:` empty (null), so a scaffold
 * submitted untouched still fails on it. Runs against the REAL `.wingfoil/memory.yaml` and the REAL
 * `.wingfoil/memory/templates/release.md`, every other required field filled in.
 */
describe('CORE_MODULES memory.memorySubmit — empty required list vs untouched scaffold (bug-147, task-168)', () => {
  const REPO_ROOT = join(__dirname, '..', '..');
  const PATH = 'docs/04_memory/planning/v1/minor-v9.9.md';
  let repo: string;

  /** The real release scaffold with every required field but `features` filled, its `features` line as given. */
  function fromScaffold(featuresLine?: string): string {
    const scaffold = readFileSync(join(REPO_ROOT, '.wingfoil/memory/templates/release.md'), 'utf-8');
    const filled = scaffold
      .replace(/^id: .*$/m, 'id: "minor-v9.9"')
      .replace(/^title: .*$/m, 'title: "A release"')
      .replace(/^kind: .*$/m, 'kind: "minor"')
      .replace(/^version: .*$/m, 'version: "v9.9"')
      .replace(/^pillar: .*$/m, 'pillar: "P1"')
      .replace(/^requirements: .*$/m, 'requirements: "docs/x.json"')
      .replace(/^release-line: .*$/m, 'release-line: "v1"');
    return featuresLine === undefined ? filled : filled.replace(/^features:.*$/m, featuresLine);
  }

  beforeEach(() => {
    repo = makeTempGitRepo();
    writeFixtureFile(repo, '.wingfoil/memory.yaml', readFileSync(join(REPO_ROOT, '.wingfoil/memory.yaml'), 'utf-8'));
    for (const name of ['release.md', 'task.md']) {
      writeFixtureFile(repo, `.wingfoil/memory/templates/${name}`, readFileSync(join(REPO_ROOT, '.wingfoil/memory/templates', name), 'utf-8'));
    }
  });

  afterEach(() => removeTempDir(repo));

  it('the untouched scaffold `features` value refuses the submit, naming features', async () => {
    writeFixtureFile(repo, PATH, fromScaffold());
    commitAll(repo, 'seed');
    const result = await memorySubmitFn()({ root: repo, positional: 'minor-v9.9' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe('missing required field on submit: features');
  });

  it('an explicit `features: []` is filled: the submit passes (draft -> planning)', async () => {
    writeFixtureFile(repo, PATH, fromScaffold('features: []'));
    commitAll(repo, 'seed');
    const result = await memorySubmitFn()({ root: repo, positional: 'minor-v9.9' });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.to).toBe('planning');
  });

  it('review ruling 1: `[]` on a field the scaffold does not declare a list (task title, release, kind) is missing', async () => {
    const path = 'docs/04_memory/v9.9/task-901-x.md';
    writeFixtureFile(
      repo,
      path,
      '---\nid: "task-901-x"\ntype: task\ntitle: []\nstatus: draft\nrelease: []\nkind: []\ntmpl_version: 260703\n---\n\nBody.\n',
    );
    commitAll(repo, 'seed');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-901-x' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe('missing required field on submit: title, release, kind');
  });

  it('re-review ruling 1: without `lists` in memory.yaml, `[]` is missing (features included) — the scaffold is not read for it', async () => {
    const config = readFileSync(join(REPO_ROOT, '.wingfoil/memory.yaml'), 'utf-8').replace(/^\s*lists: .*\n/m, '');
    writeFixtureFile(repo, '.wingfoil/memory.yaml', config);
    writeFixtureFile(repo, PATH, fromScaffold('features: []'));
    commitAll(repo, 'seed');
    const result = await memorySubmitFn()({ root: repo, positional: 'minor-v9.9' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe('missing required field on submit: features');
  });

  it('re-review ruling 2: a mapping or a list in a scalar field (task kind) is missing', async () => {
    const path = 'docs/04_memory/v9.9/task-902-x.md';
    writeFixtureFile(
      repo,
      path,
      '---\nid: "task-902-x"\ntype: task\ntitle: "T"\nstatus: draft\nrelease: [""]\nkind: {}\ntmpl_version: 260703\n---\n\nBody.\n',
    );
    commitAll(repo, 'seed');
    const result = await memorySubmitFn()({ root: repo, positional: 'task-902-x' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe('missing required field on submit: release, kind');
  });

  it('review fix 3: a separator other than the em dash names the exact form', async () => {
    writeFixtureFile(repo, PATH, fromScaffold('features: []').replace(/^pillar: .*$/m, 'pillar: "n/a - patch release"'));
    commitAll(repo, 'seed');
    const result = await memorySubmitFn()({ root: repo, positional: 'minor-v9.9' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe(
      'not-applicable value on submit: pillar must be written "n/a — <reason>", with an em dash before the reason',
    );
  });

  it('dl-124 Action 4: `pillar` and `requirements` may say "n/a — <reason>" on a release; `features` may not', async () => {
    const doc = fromScaffold('features: "n/a — patch release"')
      .replace(/^pillar: .*$/m, 'pillar: "n/a — patch release"')
      .replace(/^requirements: .*$/m, 'requirements: "n/a — no per-release backlog for a patch"');
    writeFixtureFile(repo, PATH, doc);
    commitAll(repo, 'seed');
    const result = await memorySubmitFn()({ root: repo, positional: 'minor-v9.9' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe(
      "not-applicable value on submit: features does not accept one (type 'release' does not list it in template.frontmatter.not_applicable_allowed)",
    );
  });
});

/**
 * bug-030-init-memory-yaml-has-no-state-machine (task-071) — **this block's expectation is inverted
 * from what task-045 wrote here.** It used to assert that a config with no per-type `states` and no
 * `defaults` block made `memory submit` fail with a `VALIDATION` error naming REQ-STATE-08 — and its
 * own fixture comment said that config was *"the shape `wingfoil init` scaffolds today"*. That is
 * bug-030's defect written down as an expectation: REQ-STATE-08 says such a type *"uses the default
 * machine"*, and `spec-001-memory-yaml-schema` makes `defaults` optional, so the file below is legal
 * and must work. `resolveStateMachine` now falls back to the built-in `DEFAULT_STATE_MACHINE` and the
 * submit completes. The fixture is kept exactly as it was, so the inversion is legible.
 */
describe('CORE_MODULES memory.memorySubmit — configuration with no `states` and no `defaults` (bug-030)', () => {
  let repo: string;

  beforeEach(() => {
    repo = makeTempGitRepo();
    // The shape `wingfoil init` scaffolded before task-071: types with no `states:` and no `defaults:`.
    writeFixtureFile(repo, '.wingfoil/memory.yaml', 'version: 1\ntypes:\n  task:\n    path: docs/memory/task/{id}.md\n');
    writeFixtureFile(repo, 'docs/memory/task/task-1.md', '---\nid: task-1\ntype: task\ntitle: "T"\nstatus: draft\n---\n');
    writeFixtureFile(repo, 'docs/memory/task/task-2.md', '---\nid: task-2\ntype: task\ntitle: "T"\nstatus: approved\n---\n');
    commitAll(repo, 'seed');
  });

  afterEach(() => removeTempDir(repo));

  it('submits on the built-in default machine (REQ-STATE-08): draft -> pending, one commit', async () => {
    const before = head(repo);
    const result = await memorySubmitFn()({ root: repo, positional: 'task-1' });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value).toMatchObject({ from: 'draft', to: 'pending' });
    expect(readFileSync(join(repo, 'docs/memory/task/task-1.md'), 'utf-8')).toContain('status: pending');
    expect(head(repo)).not.toBe(before);
  });

  it('still refuses an illegal verb on that machine — the fallback adds a machine, not permissiveness', async () => {
    const before = head(repo);
    // `approved` is the last state of the default `sequence`: no forward edge for `submit`.
    const result = await memorySubmitFn()({ root: repo, positional: 'task-2' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('INVALID_TRANSITION');
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
  });
});

describe('CORE_MODULES memory.memorySubmit — REQ-SEC-01 git-identity pre-flight (no configured identity)', () => {
  const ISOLATION_KEYS = ['GIT_CONFIG_GLOBAL', 'GIT_CONFIG_SYSTEM', 'GIT_CONFIG_NOSYSTEM'] as const;
  const saved: Record<string, string | undefined> = {};
  let repo: string;

  beforeEach(() => {
    repo = mkdtempSync(join(tmpdir(), 'wf-memsubmit-noid-'));
    execFileSync('git', ['-C', repo, 'init', '-q', '--initial-branch=main'], { encoding: 'utf-8' });
    const emptyConfig = join(repo, 'empty.gitconfig');
    writeFileSync(emptyConfig, '');
    for (const key of ISOLATION_KEYS) saved[key] = process.env[key];
    process.env.GIT_CONFIG_GLOBAL = emptyConfig;
    process.env.GIT_CONFIG_SYSTEM = emptyConfig;
    process.env.GIT_CONFIG_NOSYSTEM = '1';
    writeFixtureFile(repo, '.wingfoil/memory.yaml', MEMORY_YAML);
    writeFixtureFile(repo, 'docs/memory/v0.2/task-101.md', taskDoc({ id: 'task-101', status: 'draft' }));
  });

  afterEach(() => {
    for (const key of ISOLATION_KEYS) {
      if (saved[key] === undefined) delete process.env[key];
      else process.env[key] = saved[key];
    }
    rmSync(repo, { recursive: true, force: true });
  });

  it('refuses with the exact REQ-SEC-01 message (exit 1), writing nothing', async () => {
    const result = await memorySubmitFn()({ root: repo, positional: 'task-101' });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe('git identity not configured (user.name/user.email)');
    expect(exitCodeForResult(result)).toBe(1);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8')).toContain('status: draft');
  });
});
