/**
 * P1.7 (US-2-10) — `wingfoil memory approve` core-op fit criteria, per
 * `docs/02_requirements/02_bdd/features/p1-memory/P1.7-memory-approve.feature` (all three scenarios),
 * REQ-SEC-03 (role-based approval authority, `task-040`), REQ-SEC-04 (mandatory `--reason`,
 * `task-041`), `spec-010-memory-frontmatter-schema` (approve writes **only** `status`; approver and
 * reason live in the commit message), `spec-004-mcp-surface-contract` §4.3 (exactly one commit),
 * `spec-008-cli-grammar` §2/§5/§7 (bare `<id>`; missing `--reason` → `2`; business-rule refusals → `1`),
 * `dl-032` + `dl-053` (the illegal-transition message and its `<to>`) and `dl-054` (the approver-gated
 * verbs are the ones that carry the `[from → to]` subject bracket).
 *
 * Exercises the REAL, registered `CORE_MODULES` `memory.memoryApprove` operation — the exact `CoreFn`
 * the CLI command and the MCP Tool dispatch to. Every write lands in a THROWAWAY temp git repo.
 *
 * The `task` fixture type carries the REAL `task` state machine from `.wingfoil/memory.yaml`
 * (not the default machine), so both approval gates this project actually uses are exercised:
 * `pending → backlog` and the review hand-off `in-review → approved`. The `note` type falls back to
 * `defaults.states`, where `approve` lands on the literally-named `approved` state of P1.7's wording.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { CORE_MODULES } from '../../src/core';
import type { CoreFn } from '../../src/core/registry';
import { exitCodeForResult, exitCodeForThrow } from '../../src/core/exit-code';
import { UsageError } from '../../src/core/usage-error';
import { parseApprovalMetadata, verifyTransitionConsistency } from '../../src/memory/audit';
import { commitAll, makeTempGitRepo, removeTempDir, writeFixtureFile } from '../storage/helpers/git-fixture';
import { STAMP_TRAILER } from '../storage/helpers/stamp-trailer';

const MEMORY_YAML = `version: 1
defaults:
  states:
    sequence: [draft, pending, approved]
    gates:
      pending: { reject: draft }
types:
  task:
    path: "docs/memory/{release}/{id}.md"
    template:
      file: "memory/templates/task.md"
      frontmatter:
        required: [title, release]
    states:
      sequence: [draft, pending, backlog, in-progress, in-review, approved, done]
      gates:
        pending: { reject: draft }
        in-review: { reject: in-progress }
      waiting: [backlog, approved]
  note:
    path: "docs/memory/note/{id}.md"
`;

/** The git identity `makeTempGitRepo` configures — the principal every case below runs as. */
const TEST_EMAIL = 'wf-test@example.invalid';
const TEST_NAME = 'WingFoil Test';

/** `dna.yaml` in which the fixture's git identity holds `approver` (REQ-SEC-03 happy path). */
const APPROVER_DNA = `version: 1.1
modules:
  - name: core
    path: src/core
stacks:
  technologies:
    - name: TypeScript
      category: language
team:
  members:
    - name: ${TEST_NAME}
      email: ${TEST_EMAIL}
      roles: [ approver, developer ]
  roles:
    - name: approver
    - name: developer
    - name: reviewer
paths:
  sources: [ src/ ]
`;

/** The same file with the approver role withheld — BDD sc.3's "does NOT hold an approver role". */
const REVIEWER_ONLY_DNA = APPROVER_DNA.replace('roles: [ approver, developer ]', 'roles: [ reviewer, developer ]');

interface ApproveValue {
  readonly id: string;
  readonly path: string;
  readonly from: string;
  readonly to: string;
}

/** The real, registered `memory.memoryApprove` `CoreFn` — fails loudly if a future change un-registers it. */
function memoryApproveFn(): CoreFn<unknown, ApproveValue> {
  const operation = CORE_MODULES.find((module) => module.name === 'memory')?.operations.memoryApprove;
  if (!operation) throw new Error('fixture bug: "memoryApprove" operation not registered on the memory module');
  return operation.fn as CoreFn<unknown, ApproveValue>;
}

function memoryHistoryFn(): CoreFn<unknown, { entries: { operation: string | null; from: string | null; to: string | null; approver: string | null; reason: string | null }[] }> {
  const operation = CORE_MODULES.find((module) => module.name === 'memory')?.operations.memoryHistory;
  if (!operation) throw new Error('fixture bug: "memoryHistory" operation not registered');
  return operation.fn as CoreFn<unknown, { entries: { operation: string | null; from: string | null; to: string | null; approver: string | null; reason: string | null }[] }>;
}

function gitOut(repo: string, args: string[]): string {
  return execFileSync('git', ['-C', repo, ...args], { encoding: 'utf-8' }).trim();
}
const head = (repo: string): string => gitOut(repo, ['rev-parse', 'HEAD']);

function taskDoc(fields: { id: string; status: string }): string {
  return `---
id: "${fields.id}"          # auto-generated by wingfoil
type: task
title: "A task"   # REQUIRED
status: ${fields.status}          # auto-set by wingfoil
release: "v0.2"   # REQUIRED
tmpl_version: 260703
---

## Description

Real content.
`;
}

describe('CORE_MODULES memory.memoryApprove — P1.7 fit criteria', () => {
  let repo: string;

  beforeEach(() => {
    repo = makeTempGitRepo();
    writeFixtureFile(repo, '.wingfoil/memory.yaml', MEMORY_YAML);
    writeFixtureFile(repo, '.wingfoil/dna.yaml', APPROVER_DNA);
    writeFixtureFile(repo, 'docs/memory/v0.2/task-101.md', taskDoc({ id: 'task-101', status: 'pending' }));
    writeFixtureFile(repo, 'docs/memory/v0.2/task-300.md', taskDoc({ id: 'task-300', status: 'in-review' }));
    writeFixtureFile(repo, 'docs/memory/v0.2/task-200.md', taskDoc({ id: 'task-200', status: 'draft' }));
    commitAll(repo, 'seed');
  });

  afterEach(() => removeTempDir(repo));

  it('P1.7 sc.1: approves a pending document with a reason — one commit recording approver, timestamp and reason, exit 0', async () => {
    const before = head(repo);
    const result = await memoryApproveFn()({
      root: repo,
      positional: 'task-101',
      options: { reason: 'meets standards' },
    });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(exitCodeForResult(result)).toBe(0);
    expect(result.value).toEqual({ id: 'task-101', path: 'docs/memory/v0.2/task-101.md', from: 'pending', to: 'backlog' });

    // spec-010: ONLY `status` changed — the inline comment on its line and every other byte survive.
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8')).toBe(
      taskDoc({ id: 'task-101', status: 'backlog' }),
    );

    // Exactly one new commit, scoped to the one document, nothing left in the worktree.
    expect(gitOut(repo, ['rev-list', '--count', `${before}..HEAD`])).toBe('1');
    expect(gitOut(repo, ['show', '--name-only', '--format=', 'HEAD'])).toBe('docs/memory/v0.2/task-101.md');
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');

    // dl-054 + CLAUDE.md §5.1: subject carries `[from → to]`; body carries `Approver:` and `Reason:`.
    const message = `wf(task): approve task-101 [pending → backlog]\n\nApprover: ${TEST_NAME} <${TEST_EMAIL}> (approver)\nReason: meets standards`;
    expect(gitOut(repo, ['log', '-1', '--format=%B'])).toBe(`${message}${STAMP_TRAILER}`);
    // `CoreResult.commit.message` is the operation's message; the signature is commitPaths' (task-192).
    expect(result.commit).toEqual({ sha: head(repo), message });

    // P1.7's ISO-8601 timestamp is git's own, never written into the message (P1.2/P1.10). The zone
    // must be explicit, but either legal spelling of it counts: git >= 2.55 renders a zero offset as
    // `Z` where 2.43 wrote `+00:00`, so demanding `[+-]HH:MM` fails on any UTC runner (bug-057).
    expect(gitOut(repo, ['log', '-1', '--format=%aI'])).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:Z|[+-]\d{2}:\d{2})$/);
  });

  it('P1.7 sc.1: the review hand-off gate reaches the literally-named `approved` state (in-review → approved)', async () => {
    const result = await memoryApproveFn()({ root: repo, positional: 'task-300', options: { reason: 'tests pass' } });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.from).toBe('in-review');
    expect(result.value.to).toBe('approved');
    expect(result.commit?.message.split('\n')[0]).toBe('wf(task): approve task-300 [in-review → approved]');
  });

  it('P1.7 sc.1: a type falling back to `defaults.states` approves pending → approved (REQ-STATE-08)', async () => {
    writeFixtureFile(repo, 'docs/memory/note/note-1.md', '---\nid: note-1\ntype: note\ntitle: "N"\nstatus: pending\n---\nbody\n');
    commitAll(repo, 'seed note');
    const result = await memoryApproveFn()({ root: repo, positional: 'note-1', options: { reason: 'ok' } });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.to).toBe('approved');
    expect(result.commit?.message.split('\n')[0]).toBe('wf(note): approve note-1 [pending → approved]');
  });

  it('P1.7 sc.2: omitting `--reason` exits 2 with the exact REQ-SEC-04 message and changes nothing', async () => {
    const before = head(repo);
    const original = readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8');
    for (const options of [undefined, {}, { format: 'json' }]) {
      await expect(memoryApproveFn()({ root: repo, positional: 'task-101', options })).rejects.toBeInstanceOf(UsageError);
      try {
        await memoryApproveFn()({ root: repo, positional: 'task-101', options });
      } catch (error) {
        expect(exitCodeForThrow(error)).toEqual({ reason: 'missing required argument: --reason', exitCode: 2 });
      }
    }
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8')).toBe(original);
    expect(head(repo)).toBe(before);
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');
  });

  it('P1.7 sc.3: a caller holding no `approver` role exits 1 with the REQ-SEC-03 message, state unchanged', async () => {
    writeFixtureFile(repo, '.wingfoil/dna.yaml', REVIEWER_ONLY_DNA);
    commitAll(repo, 'reviewer-only dna');
    const before = head(repo);
    const original = readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8');

    const result = await memoryApproveFn()({ root: repo, positional: 'task-101', options: { reason: 'ok' } });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('VALIDATION');
    expect(result.error.message).toBe("user not authorized to approve type 'task'");
    expect(exitCodeForResult(result)).toBe(1);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8')).toBe(original);
    expect(head(repo)).toBe(before);
    expect(gitOut(repo, ['status', '--porcelain'])).toBe('');
  });

  it('P1.7 sc.3: the refusal names the document\'s OWN type, not a fixed one', async () => {
    writeFixtureFile(repo, '.wingfoil/dna.yaml', REVIEWER_ONLY_DNA);
    writeFixtureFile(repo, 'docs/memory/note/note-2.md', '---\nid: note-2\ntype: note\ntitle: "N"\nstatus: pending\n---\nbody\n');
    commitAll(repo, 'reviewer-only dna + note');
    const result = await memoryApproveFn()({ root: repo, positional: 'note-2', options: { reason: 'ok' } });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe("user not authorized to approve type 'note'");
  });

  it('dl-032/dl-053: approving a `draft` task is refused with the pinned contract message (exit 1), writing nothing', async () => {
    const before = head(repo);
    const result = await memoryApproveFn()({ root: repo, positional: 'task-200', options: { reason: 'ok' } });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('INVALID_TRANSITION');
    // task-181 (bug-165): `<to>` is what `approve` reaches from `draft` — nothing, so `(none)`; never
    // `approve`'s edge from another state (`pending -> backlog`) nor the next `sequence` state.
    expect(result.error.message).toBe("illegal transition draft -> (none) for type 'task'");
    expect(exitCodeForResult(result)).toBe(1);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-200.md'), 'utf-8')).toContain('status: draft');
    expect(head(repo)).toBe(before);
  });

  it('a non-existent document exits 1 with `document not found: task-999`', async () => {
    const before = head(repo);
    const result = await memoryApproveFn()({ root: repo, positional: 'task-999', options: { reason: 'ok' } });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('NOT_FOUND');
    expect(result.error.message).toBe('document not found: task-999');
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
  });

  it('a missing or blank `<id>` is a usage error (exit 2) — spec-008 §5/§7', async () => {
    for (const positional of [undefined, '  ']) {
      await expect(
        memoryApproveFn()({ root: repo, positional, options: { reason: 'ok' } }),
      ).rejects.toBeInstanceOf(UsageError);
      try {
        await memoryApproveFn()({ root: repo, positional, options: { reason: 'ok' } });
      } catch (error) {
        expect(exitCodeForThrow(error)).toEqual({ reason: 'missing required argument: memory approve <id>', exitCode: 2 });
      }
    }
  });

  it('a malformed `dna.yaml` is a VALIDATION error (exit 1), never an escaped throw, and writes nothing', async () => {
    writeFixtureFile(repo, '.wingfoil/dna.yaml', 'version: 1.1\nmodules: "not a list"\n');
    commitAll(repo, 'broken dna');
    const before = head(repo);
    const result = await memoryApproveFn()({ root: repo, positional: 'task-101', options: { reason: 'ok' } });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(exitCodeForResult(result)).toBeGreaterThan(0);
    expect(head(repo)).toBe(before);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8')).toContain('status: pending');
  });

  it('dl-054: the approve commit is cross-checkable — `verifyTransitionConsistency` finds no drift between bracket and frontmatter', async () => {
    await memoryApproveFn()({ root: repo, positional: 'task-101', options: { reason: 'meets standards' } });
    expect(verifyTransitionConsistency(repo, 'docs/memory/v0.2/task-101.md')).toEqual([]);
  });

  it('P1.7: the commit body round-trips through `parseApprovalMetadata` (identity + reason recoverable)', async () => {
    await memoryApproveFn()({ root: repo, positional: 'task-101', options: { reason: 'meets standards' } });
    expect(parseApprovalMetadata(gitOut(repo, ['log', '-1', '--format=%b']))).toEqual({
      approverName: TEST_NAME,
      approverEmail: TEST_EMAIL,
      approverRole: 'approver',
      reason: 'meets standards',
    });
  });

  it('`memory history` reads the approve back as operation `approve`, pending -> backlog (P1.10 round-trip)', async () => {
    await memoryApproveFn()({ root: repo, positional: 'task-101', options: { reason: 'meets standards' } });
    const history = await memoryHistoryFn()({ root: repo, positional: 'task-101' });
    expect(history.ok).toBe(true);
    if (!history.ok) return;
    const last = history.value.entries[history.value.entries.length - 1];
    expect(last).toMatchObject({ operation: 'approve', from: 'pending', to: 'backlog', reason: 'meets standards' });
  });

  it('bug-027: a change someone else staged is NOT swept into the `wf(task): approve` commit, and stays staged', async () => {
    writeFixtureFile(repo, 'other.txt', 'unrelated work');
    gitOut(repo, ['add', 'other.txt']);
    const result = await memoryApproveFn()({ root: repo, positional: 'task-101', options: { reason: 'ok' } });
    expect(result.ok).toBe(true);
    expect(gitOut(repo, ['show', '--name-only', '--format=', 'HEAD'])).toBe('docs/memory/v0.2/task-101.md');
    expect(gitOut(repo, ['diff', '--cached', '--name-only'])).toBe('other.txt');
  });

  it('a `status` that is not a state of the type exits 1 with the task-036 message, writing nothing', async () => {
    writeFixtureFile(repo, 'docs/memory/v0.2/task-105.md', taskDoc({ id: 'task-105', status: 'shipped' }));
    commitAll(repo, 'seed 105');
    const before = head(repo);
    const result = await memoryApproveFn()({ root: repo, positional: 'task-105', options: { reason: 'ok' } });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.code).toBe('VALIDATION');
    expect(result.error.message).toBe("invalid state 'shipped' for type 'task'");
    expect(exitCodeForResult(result)).toBe(1);
    expect(head(repo)).toBe(before);
  });
});

describe('CORE_MODULES memory.memoryApprove — REQ-SEC-01 git-identity pre-flight (no configured identity)', () => {
  // task-125 (review finding 2): the seven other mutating verbs pin this case; approve did not.
  const ISOLATION_KEYS = ['GIT_CONFIG_GLOBAL', 'GIT_CONFIG_SYSTEM', 'GIT_CONFIG_NOSYSTEM'] as const;
  const saved: Record<string, string | undefined> = {};
  let repo: string;

  beforeEach(() => {
    repo = mkdtempSync(join(tmpdir(), 'wf-memapprove-noid-'));
    execFileSync('git', ['-C', repo, 'init', '-q', '--initial-branch=main'], { encoding: 'utf-8' });
    const emptyConfig = join(repo, 'empty.gitconfig');
    writeFileSync(emptyConfig, '');
    for (const key of ISOLATION_KEYS) saved[key] = process.env[key];
    process.env.GIT_CONFIG_GLOBAL = emptyConfig;
    process.env.GIT_CONFIG_SYSTEM = emptyConfig;
    process.env.GIT_CONFIG_NOSYSTEM = '1';
    writeFixtureFile(repo, '.wingfoil/memory.yaml', MEMORY_YAML);
    writeFixtureFile(repo, '.wingfoil/dna.yaml', APPROVER_DNA);
    writeFixtureFile(repo, 'docs/memory/v0.2/task-101.md', taskDoc({ id: 'task-101', status: 'pending' }));
  });

  afterEach(() => {
    for (const key of ISOLATION_KEYS) {
      if (saved[key] === undefined) delete process.env[key];
      else process.env[key] = saved[key];
    }
    rmSync(repo, { recursive: true, force: true });
  });

  it('with valid arguments, refuses with the exact REQ-SEC-01 message (exit 1) before any authority check, writing nothing', async () => {
    const result = await memoryApproveFn()({ root: repo, positional: 'task-101', options: { reason: 'x' } });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message).toBe('git identity not configured (user.name/user.email)');
    expect(exitCodeForResult(result)).toBe(1);
    expect(readFileSync(join(repo, 'docs/memory/v0.2/task-101.md'), 'utf-8')).toContain('status: pending');
  });
});
