/**
 * task-110-memory-add-keeps-version-dots-and-sources-every-id-token — `memory add` gives every
 * `id_pattern` token a declared source (`dl-107` S2 (a)+(c), ratified at `35d163af`), per
 * `spec-001-memory-yaml-schema`'s id_pattern section (amended `0f68c739`, fixed `33d89b7c`) and the
 * `--set <name>=<value>` option `spec-008-cli-grammar` §10 defines.
 *
 * Exercised at the `CoreFn` seam through the REAL registered `memory.memoryAdd`, in a throwaway git
 * repo whose `memory.yaml` mirrors this repository's own `release`, `release-line` and `plan` types
 * (`.wingfoil/memory.yaml`): `{kind}-{version}` under an `rl-{release-line}` path folder (task-164),
 * `rl-{version}`, and `{workflow}-{phase}-plan` under a `{scope}` path folder. The CLI surface hands
 * the repeatable option as a string array under `options.set` (`src/cli/program.ts`).
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { CORE_MODULES } from '../../src/core';
import type { CoreFn } from '../../src/core/registry';
import { exitCodeForResult } from '../../src/core/exit-code';
import { UsageError } from '../../src/core/usage-error';
import { commitAll, makeTempGitRepo, removeTempDir, writeFixtureFile } from '../storage/helpers/git-fixture';

const MEMORY_YAML = `version: 1
types:
  release-line:
    path: "docs/memory/planning/{id}.md"
    id_pattern: "rl-{version}"
    template:
      file: "memory/templates/release-line.md"
      frontmatter:
        required: [id, type, title, status]
  release:
    path: "docs/memory/planning/rl-{release-line}/{id}.md"
    id_pattern: "{kind}-{version}"
    template:
      file: "memory/templates/release.md"
      frontmatter:
        required: [id, type, title, status]
  plan:
    path: "docs/plans/{scope}/{id}.md"
    id_pattern: "{workflow}-{phase}-plan"
    template:
      file: "memory/templates/plan.md"
      frontmatter:
        required: [id, type, title, status]
  counted:
    path: "docs/memory/counted/{id}.md"
    id_pattern: "rel-{kind}-{n}"
    template:
      file: "memory/templates/counted.md"
      frontmatter:
        required: [id, type, title, status]
  decision:
    path: "docs/memory/decision/{id}.md"
    id_pattern: "dl-{n}-{slug}"
    template:
      file: "memory/templates/counted.md"
      frontmatter:
        required: [id, type, title, status]
  dated:
    path: "docs/memory/dated/{id}.md"
    id_pattern: "d-{date}-{slug}"
    template:
      file: "memory/templates/counted.md"
      frontmatter:
        required: [id, type, title, status]
`;

const RELEASE_LINE_TEMPLATE = `---
id: "{auto}"           # auto-generated by wingfoil
type: release-line
title: ""              # REQUIRED
status: draft          # auto-set by wingfoil
version: ""            # REQUIRED — e.g. "v1"
tmpl_version: 260703
---

## Scope
`;

const RELEASE_TEMPLATE = `---
id: "{auto}"           # auto-generated by wingfoil
type: release
title: ""              # REQUIRED
status: draft          # auto-set by wingfoil
kind: ""               # REQUIRED — "minor" or "patch"
patch-of: ""           # optional
version: ""            # REQUIRED — e.g. "v0.1"
release-line: ""       # REQUIRED — also the path folder for this file
tmpl_version: 260929
---

## Scope
`;

const PLAN_TEMPLATE = `---
id: "{auto}"
type: plan
title: ""
status: draft
workflow: ""           # REQUIRED
phase: ""              # REQUIRED
tmpl_version: 260703
---

## Context
`;

const COUNTED_TEMPLATE = `---
id: ""
type: counted
title: ""
status: draft
tmpl_version: 260101
---

body
`;

function memoryAddFn(): CoreFn<unknown, { id: string; path: string }> {
  const operation = CORE_MODULES.find((module) => module.name === 'memory')?.operations.memoryAdd;
  if (!operation) throw new Error('fixture bug: "memoryAdd" operation not registered on the memory module');
  return operation.fn as CoreFn<unknown, { id: string; path: string }>;
}

const head = (repo: string): string => execFileSync('git', ['-C', repo, 'rev-parse', 'HEAD'], { encoding: 'utf-8' }).trim();
const subject = (repo: string): string =>
  execFileSync('git', ['-C', repo, 'log', '-1', '--format=%s'], { encoding: 'utf-8' }).trim();

/** Run `memory add` expecting a `UsageError` (exit 2); returns its message. */
async function usageError(repo: string, options: Record<string, unknown>): Promise<string> {
  try {
    await memoryAddFn()({ root: repo, options });
  } catch (error) {
    expect(error).toBeInstanceOf(UsageError);
    expect((error as UsageError).exitCode).toBe(2);
    return (error as UsageError).message;
  }
  throw new Error('expected a UsageError');
}

describe('memory add — id_pattern tokens sourced from --set (task-110, dl-107 S2)', () => {
  let repo: string;

  beforeEach(() => {
    repo = makeTempGitRepo();
    writeFixtureFile(repo, '.wingfoil/memory.yaml', MEMORY_YAML);
    writeFixtureFile(repo, '.wingfoil/memory/templates/release-line.md', RELEASE_LINE_TEMPLATE);
    writeFixtureFile(repo, '.wingfoil/memory/templates/release.md', RELEASE_TEMPLATE);
    writeFixtureFile(repo, '.wingfoil/memory/templates/plan.md', PLAN_TEMPLATE);
    writeFixtureFile(repo, '.wingfoil/memory/templates/counted.md', COUNTED_TEMPLATE);
    commitAll(repo, 'seed memory.yaml + templates');
  });

  afterEach(() => {
    removeTempDir(repo);
  });

  describe('AC 2 — a {<field>} token takes its value from --set and writes it back', () => {
    it('{kind}-{version} under an rl-{release-line} folder produces patch-v0.2.3, dots kept, fields written', async () => {
      const result = await memoryAddFn()({
        root: repo,
        options: { type: 'release', title: 'WingFoil v0.2.3', set: ['kind=patch', 'version=v0.2.3', 'release-line=v1'] },
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(result.value.id).toBe('patch-v0.2.3');
      expect(result.value.path).toBe('docs/memory/planning/rl-v1/patch-v0.2.3.md');
      expect(subject(repo)).toBe('wf(release): add patch-v0.2.3');

      const content = readFileSync(join(repo, result.value.path), 'utf-8');
      expect(content).toContain('id: patch-v0.2.3');
      expect(content).toMatch(/^kind: "patch"(?: +#.*)?$/m);
      expect(content).toMatch(/^version: "v0.2.3"(?: +#.*)?$/m);
      expect(content).toMatch(/^release-line: "v1"(?: +#.*)?$/m);
      // A field no --set named keeps the scaffold's default, comment included; since task-163
      // (`bug-033`) a field --set fills keeps its comment as well.
      expect(content).toContain('kind: "patch"               # REQUIRED — "minor" or "patch"');
      expect(content).toContain('patch-of: ""           # optional');
    });

    it('a single-string --set (one occurrence) is accepted like a one-element list', async () => {
      const result = await memoryAddFn()({
        root: repo,
        options: { type: 'release-line', title: 'WingFoil v2', set: 'version=v2' },
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(result.value.id).toBe('rl-v2');
      expect(readFileSync(join(repo, result.value.path), 'utf-8')).toMatch(/^version: "v2"(?: +#.*)?$/m);
    });

    it('splits name from value at the FIRST "=" only', async () => {
      const result = await memoryAddFn()({
        root: repo,
        options: { type: 'plan', title: 'P', set: ['workflow=dev-loop', 'phase=rel-v0.3', 'scope=a=b'] },
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(result.value.path).toBe('docs/plans/a=b/dev-loop-rel-v0.3-plan.md');
    });

    it('a token with no value fails naming the token and the option, writing nothing (exit 1)', async () => {
      const before = head(repo);
      const result = await memoryAddFn()({
        root: repo,
        options: { type: 'release', title: 'X', set: ['kind=patch', 'release-line=v1'] },
      });
      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.error.code).toBe('VALIDATION');
      expect(result.error.message).toBe('missing value for token {version}: give it with --set version=<value>');
      expect(exitCodeForResult(result)).toBe(1);
      expect(head(repo)).toBe(before);
    });

    it('every missing token is named, in pattern order', async () => {
      const result = await memoryAddFn()({ root: repo, options: { type: 'release', title: 'X', set: ['release-line=v1'] } });
      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.error.message).toBe(
        'missing value for token {kind}: give it with --set kind=<value>; ' +
          'missing value for token {version}: give it with --set version=<value>',
      );
    });

    it('a value outside the id character class is a validation error naming the token (exit 1)', async () => {
      const before = head(repo);
      const result = await memoryAddFn()({
        root: repo,
        options: { type: 'release', title: 'X', set: ['kind=patch', 'version=V0.2', 'release-line=v1'] },
      });
      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.error.code).toBe('VALIDATION');
      expect(result.error.message).toBe('value for token {version} is not a valid [a-z0-9-.] piece: "V0.2"');
      expect(head(repo)).toBe(before);
    });

    it('a --set name the type has no token for is refused (exit 1), naming the type', async () => {
      const before = head(repo);
      const result = await memoryAddFn()({
        root: repo,
        options: { type: 'release-line', title: 'X', set: ['version=v2', 'pillar=P1'] },
      });
      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.error.code).toBe('VALIDATION');
      expect(result.error.message).toBe("--set pillar: memory type 'release-line' has no token {pillar} in its id_pattern or path");
      expect(exitCodeForResult(result)).toBe(1);
      expect(head(repo)).toBe(before);
    });

    it('field tokens materialize BEFORE {n}: the counter sees the fully-materialized prefix (spec-001 order)', async () => {
      const minor = await memoryAddFn()({ root: repo, options: { type: 'counted', title: 'A', set: ['kind=minor'] } });
      const patch = await memoryAddFn()({ root: repo, options: { type: 'counted', title: 'B', set: ['kind=patch'] } });
      const minor2 = await memoryAddFn()({ root: repo, options: { type: 'counted', title: 'C', set: ['kind=minor'] } });
      expect(minor.ok && patch.ok && minor2.ok).toBe(true);
      if (!minor.ok || !patch.ok || !minor2.ok) return;
      expect(minor.value.id).toBe('rel-minor-001');
      expect(patch.value.id).toBe('rel-patch-001');
      expect(minor2.value.id).toBe('rel-minor-002');
    });

    it('a {n}-{slug} type with no --set behaves exactly as before, and keeps version dots in its slug', async () => {
      const result = await memoryAddFn()({ root: repo, options: { type: 'decision', title: 'Retrospective v0.2' } });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(result.value.id).toBe('dl-001-retrospective-v0.2');
    });

    it('{date} is no longer a missing token: it expands to an 8-digit date (task-163, bug-158)', async () => {
      const result = await memoryAddFn()({ root: repo, options: { type: 'dated', title: 'X' } });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(result.value.id).toMatch(/^d-[0-9]{8}-x$/);
    });
  });

  describe('AC 3 — {workflow}, {phase}, {scope} from the CLI', () => {
    it('fills the plan id and its {scope} folder; workflow/phase written (the template has them), scope not', async () => {
      const result = await memoryAddFn()({
        root: repo,
        options: {
          type: 'plan',
          title: 'Dev-loop — rel-v0.2.3',
          set: ['workflow=dev-loop', 'phase=rel-v0.2.3', 'scope=rl-v1/rel-v0.2.3'],
        },
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(result.value.id).toBe('dev-loop-rel-v0.2.3-plan');
      expect(result.value.path).toBe('docs/plans/rl-v1/rel-v0.2.3/dev-loop-rel-v0.2.3-plan.md');
      const content = readFileSync(join(repo, result.value.path), 'utf-8');
      expect(content).toMatch(/^workflow: "dev-loop"(?: +#.*)?$/m);
      expect(content).toMatch(/^phase: "rel-v0.2.3"(?: +#.*)?$/m);
      expect(content).not.toMatch(/^scope:/m);
    });

    it('a path token still missing keeps its storage refusal (exit 1), writing nothing', async () => {
      const before = head(repo);
      const result = await memoryAddFn()({
        root: repo,
        options: { type: 'plan', title: 'X', set: ['workflow=dev-loop', 'phase=p'] },
      });
      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.error.code).toBe('IO');
      expect(result.error.message).toContain('scope');
      expect(head(repo)).toBe(before);
      expect(existsSync(join(repo, 'docs/plans'))).toBe(false);
    });
  });

  describe('spec-008 §10 — spelling faults are usage errors (exit 2), raised before anything is written', () => {
    it.each([
      [['version'], 'invalid flag value: --set expects <name>=<value>, got "version"'],
      [['=v1'], 'invalid flag value: --set expects <name>=<value>, got "=v1"'],
      [['release.version=v1'], 'invalid flag value: --set name "release.version" is not a field name ([a-z][a-z0-9_-]*)'],
      [['Version=v1'], 'invalid flag value: --set name "Version" is not a field name ([a-z][a-z0-9_-]*)'],
      [['version=  '], 'invalid flag value: --set version must not be blank'],
      [['version=v1', 'version=v2'], 'invalid flag value: --set version given more than once'],
      [['slug=x'], 'invalid flag value: --set cannot set "slug": memory add fills it itself or through its own option'],
      [['n=3'], 'invalid flag value: --set cannot set "n": memory add fills it itself or through its own option'],
      [['id=x'], 'invalid flag value: --set cannot set "id": memory add fills it itself or through its own option'],
      [['title=x'], 'invalid flag value: --set cannot set "title": memory add fills it itself or through its own option'],
      [
        ['date=20260929'],
        'invalid flag value: --set cannot set "date": memory add fills {date} from the add commit\'s author date (GIT_AUTHOR_DATE, or the clock)',
      ],
    ])('--set %j → %s', async (set, message) => {
      const before = head(repo);
      expect(await usageError(repo, { type: 'release-line', title: 'X', set })).toBe(message);
      expect(head(repo)).toBe(before);
    });
  });
});
