/**
 * task-209 — `wingfoil memory submit` declares, in its commit, the content it carries (`dl-106`
 * W1 (a); `bug-146`), and its subject follows the approver's ruling (`dl-054` over `dl-106` W1 (a),
 * release-planning ruling R20: `wf(<type>): submit <id>`, no bracket).
 *
 * BDD: `P1.6-memory-submit.feature`, scenario "Submit carries the author's content and declares it".
 *
 * Exercises the REAL, registered `memory.memorySubmit` `CoreFn` on a throw-away repository, and reads
 * back the commit git recorded (`git cat-file commit`, which `%B` would pad with a newline git does not
 * store).
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { CORE_MODULES } from '../../src/core';
import type { CoreFn } from '../../src/core/registry';
import { commitAll, makeTempGitRepo, removeTempDir, writeFixtureFile } from '../storage/helpers/git-fixture';
import { STAMP_TRAILER } from '../storage/helpers/stamp-trailer';

const MEMORY_YAML = `version: 1
defaults:
  states:
    sequence: [draft, pending, approved]
    gates:
      pending: { reject: draft }
types:
  task:
    path: "docs/memory/{release}/{id}.md"
    template:
      file: "memory/templates/task.md"
      frontmatter:
        required: [title, release]
    states:
      sequence: [draft, pending, backlog, in-progress, in-review, approved, done]
      gates:
        pending: { reject: draft }
        in-review: { reject: in-progress }
      waiting: [backlog, approved]
`;

const PATH = 'docs/memory/v0.2/task-101.md';

function taskDoc(fields: { state?: string; title?: string; extra?: string; body?: string } = {}): string {
  return `---
id: "task-101"          # auto-generated by wingfoil
type: task
title: "${fields.title ?? 'A task'}"   # REQUIRED
status: ${fields.state ?? 'draft'}          # auto-set by wingfoil
release: "v0.2"   # REQUIRED
${fields.extra ?? ''}tmpl_version: 260703
---

${fields.body ?? '## Description\n\nReal content.\n'}`;
}

function memoryFn(name: string): CoreFn<unknown, unknown> {
  const operation = CORE_MODULES.find((module) => module.name === 'memory')?.operations[name];
  if (!operation) throw new Error(`fixture bug: "${name}" operation not registered on the memory module`);
  return operation.fn as CoreFn<unknown, unknown>;
}

function git(repo: string, args: string[]): string {
  return execFileSync('git', ['-C', repo, ...args], { encoding: 'utf-8' });
}

/** The commit message exactly as git stores it (no padding newline). */
function storedMessage(repo: string): string {
  const raw = git(repo, ['cat-file', 'commit', 'HEAD']);
  return raw.slice(raw.indexOf('\n\n') + 2).replace(/\n$/, '');
}

describe('memory submit declares the content it carries (task-209, dl-106 W1 (a), bug-146)', () => {
  let repo: string;

  beforeEach(() => {
    repo = makeTempGitRepo();
    writeFixtureFile(repo, '.wingfoil/memory.yaml', MEMORY_YAML);
    writeFixtureFile(repo, PATH, taskDoc());
    commitAll(repo, 'seed');
  });

  afterEach(() => removeTempDir(repo));

  const submit = async (): Promise<{ ok: boolean; commit?: { message: string } }> =>
    (await memoryFn('memorySubmit')({ root: repo, positional: 'task-101' })) as { ok: boolean; commit?: { message: string } };

  it('BDD P1.6 "Submit carries the author\'s content and declares it": a body edit is named "the body"', async () => {
    writeFileSync(join(repo, PATH), taskDoc({ body: '## Description\n\nFinished content.\n' }));
    const result = await submit();
    expect(result.ok).toBe(true);
    const message = 'wf(task): submit task-101\n\nCarries content: the body';
    expect(result.commit?.message).toBe(message);
    expect(storedMessage(repo)).toBe(`${message}${STAMP_TRAILER}`);
    expect(git(repo, ['show', 'HEAD:' + PATH])).toContain('Finished content.');
  });

  it('frontmatter edits list every changed field, sorted, before the body', async () => {
    writeFileSync(join(repo, PATH), taskDoc({ title: 'A better task', extra: 'priority: "high"\n', body: 'New body.\n' }));
    const result = await submit();
    expect(result.ok).toBe(true);
    expect(storedMessage(repo)).toBe(
      `wf(task): submit task-101\n\nCarries content: frontmatter field 'priority', frontmatter field 'title', the body${STAMP_TRAILER}`,
    );
  });

  it('a pure transition writes no such line: the subject alone, then the build stamp', async () => {
    const result = await submit();
    expect(result.ok).toBe(true);
    expect(result.commit?.message).toBe('wf(task): submit task-101');
    expect(storedMessage(repo)).toBe(`wf(task): submit task-101${STAMP_TRAILER}`);
  });

  it("a resubmit that only clears `rejection_reason` (the submit's own field) declares nothing", async () => {
    writeFileSync(join(repo, PATH), taskDoc({ extra: 'rejection_reason: "add ACs"\n' }));
    commitAll(repo, 'seed rejected');
    const result = await submit();
    expect(result.ok).toBe(true);
    expect(storedMessage(repo)).toBe(`wf(task): submit task-101${STAMP_TRAILER}`);
    expect(readFileSync(join(repo, PATH), 'utf-8')).not.toContain('rejection_reason');
  });

  it('the subject follows the F1 ruling (dl-054, R20): plain `wf(<type>): submit <id>`, no bracket, with or without content', async () => {
    writeFileSync(join(repo, PATH), taskDoc({ body: 'x\n' }));
    await submit();
    expect(git(repo, ['log', '-1', '--format=%s'])).toBe('wf(task): submit task-101\n');
  });

  describe('line endings (review F1)', () => {
    const crlf = (text: string): string => text.replace(/\n/g, '\r\n');

    it('no line-ending filter: a field edit plus a CRLF conversion declares the field AND the line endings (re-review 1)', async () => {
      git(repo, ['config', 'core.autocrlf', 'false']);
      writeFileSync(join(repo, PATH), crlf(taskDoc({ extra: 'priority: "high"\n' })));
      const result = await submit();
      expect(result.ok).toBe(true);
      expect(result.commit?.message).toBe("wf(task): submit task-101\n\nCarries content: frontmatter field 'priority', the line endings");
    });

    it('core.autocrlf=true: a field edit on a CRLF working tree declares the field only', async () => {
      git(repo, ['config', 'core.autocrlf', 'true']);
      writeFileSync(join(repo, PATH), crlf(taskDoc({ extra: 'priority: "high"\n' })));
      const result = await submit();
      expect(result.ok).toBe(true);
      expect(result.commit?.message).toBe("wf(task): submit task-101\n\nCarries content: frontmatter field 'priority'");
    });

    it('core.autocrlf=input normalizes as well: a CRLF working tree over an LF blob declares nothing', async () => {
      git(repo, ['config', 'core.autocrlf', 'input']);
      writeFileSync(join(repo, PATH), crlf(taskDoc()));
      const result = await submit();
      expect(result.ok).toBe(true);
      expect(result.commit?.message).toBe('wf(task): submit task-101');
    });

    it('core.autocrlf=true: a pure transition on a CRLF working tree over an LF blob declares nothing', async () => {
      git(repo, ['config', 'core.autocrlf', 'true']);
      writeFileSync(join(repo, PATH), crlf(taskDoc()));
      const result = await submit();
      expect(result.ok).toBe(true);
      expect(result.commit?.message).toBe('wf(task): submit task-101');
    });

    it('core.autocrlf=true: a body edit on a CRLF working tree declares "the body" and nothing else', async () => {
      git(repo, ['config', 'core.autocrlf', 'true']);
      writeFileSync(join(repo, PATH), crlf(taskDoc({ body: '## Description\n\nFinished.\n' })));
      const result = await submit();
      expect(result.ok).toBe(true);
      expect(result.commit?.message).toBe('wf(task): submit task-101\n\nCarries content: the body');
    });

    it('no line-ending filter: converting the document to CRLF is content git commits, declared as "the line endings"', async () => {
      // Pinned per repository: a developer's global config may set core.autocrlf (input normalizes CRLF too).
      git(repo, ['config', 'core.autocrlf', 'false']);
      writeFileSync(join(repo, PATH), crlf(taskDoc()));
      const result = await submit();
      expect(result.ok).toBe(true);
      expect(result.commit?.message).toBe('wf(task): submit task-101\n\nCarries content: the line endings');
    });
  });

  it('`memory history` still reads the content-carrying submit as `submit`, draft -> pending', async () => {
    writeFileSync(join(repo, PATH), taskDoc({ body: 'x\n' }));
    await submit();
    const history = (await memoryFn('memoryHistory')({ root: repo, positional: 'task-101' })) as {
      ok: boolean;
      value: { entries: { operation: string | null; from: string | null; to: string | null; reason?: unknown; approver?: unknown }[] };
    };
    expect(history.ok).toBe(true);
    const last = history.value.entries[history.value.entries.length - 1];
    expect(last).toMatchObject({ operation: 'submit', from: 'draft', to: 'pending' });
    expect(last?.reason ?? null).toBeNull();
    expect(last?.approver ?? null).toBeNull();
  });
});
